name: 'Avalon' # used in page titles
fedora:
  namespace: avalon
domain:
  host: localhost
  port: 80
  protocol: http
dropbox:
  path: '/srv/avalon/dropbox/'
  upload_uri: 'sftp://localhost/srv/avalon/dropbox'
matterhorn:
  root: 'http://localhost:8080/'
  baseApplication: 'avalon'
  cleanup_log: 'log/cleanup_jobs.log'
mediainfo:
  path: '/usr/bin/mediainfo'
ffmpeg:
  path: 'usr/local/ffmpeg'
email:
  comments: 'avalon-comments@example.edu'
  notification: 'avalon-notifications@example.edu'
  support: 'avalon-support@example.edu'
  mailer:
    smtp:
      address: 'smtp.example.edu'
      port: 587
      enable_starttls_auto: false
solr:
  collection: avalon
  configset: <%= File.join(Rails.root, 'solr', 'config') %>
zookeeper:
  connection_str: "localhost:9983/configs"
streaming:
  stream_token_ttl: 20 #minutes
  content_path: '/srv/avalon/content'
  rtmp_base: 'rtmp://localhost/avalon'
  http_base: 'http://localhost:3000/streams'
  default_quality: 'low'
groups:
  system_groups: [administrator, group_manager, manager]
master_file_management:
  strategy: 'none' #'delete', or 'move' (for move uncomment and configure next line)
  #path: '/path/to/move/to'
bib_retriever:
  protocol: sru
  url: http://zgate.example.edu:9000/exampledb
  query: rec.id='%s'
controlled_vocabulary:
  path: config/controlled_vocabulary.yml
